model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: ${logger.monitor_metric}
#    monitor: 'train_acc5'
    save_top_k: 1           # save k best models (determined by above metric)
    save_last: true         # additionaly always save model from last epoch
    mode: ${logger.monitor_metric_mode}
#    mode: 'max'
    verbose: true
    dirpath: '/data/zhangpeng/fane/checkpoints/vit_full_loss_threshold_0.95/'
    filename: 'pretrain-{epoch:04d}'
