user: aaai2026-6639
project_name: AAAI2026-FaNe
seed: 114514
debug: false
running_time: ${now:%Y-%m-%d-%H-%M-%S}
num_workers: 16
tags: 
work_dir: ${hydra:runtime.cwd}

hydra:
  output_subdir: hydra
  run:
    dir: ../logs/${experiment_name}
  job:
    env_set: 
      TOKENIZERS_PARALLELISM: "false"
      
