_target_: fane.models.fane.Fane
text_encoder: ???
image_encoder: ???
gpus: ${trainer.gpus}
batch_size: 72
optim: adam
max_epochs: 100
stage1_learning_rate: 2e-5
stage1_learning_rate_start: 1e-8
stage1_learning_rate_end: 2e-5
stage1_weight_decay: 1e-6
stage1_warmup_epochs: 20
temperature: 0.01
local_temperature: 0.01
intra_temperature: 0.01
embed_dim: 128
exclude_bn_bias: False
num_workers: ${num_workers}
frozen_text_encoder: false
ckpt_path: '/data/zhangpeng/fane/checkpoints/'
image_rec_drop_out_rate: 0.5
lambda_proto: 10
spb_k: 512
temp_decay: fixed
gahter_pool: avg



